-- MauCookie: buildings, generated from the original game's data (version 2.052).
-- Do not edit by hand; regenerate with scratchpad ccgen/gen-lua.js.

local _, NS = ...

NS.BUILDINGS = {
	{ id = 0, name = "Cursor", plural = "cursors", single = "cursor", bsingle = "cursor", bplural = "cursors", desc = "Autoclicks once every 10 seconds.",
		basePrice = 15, baseCps = 1e-1, iconColumn = 0, icon = 0, n = 0,
		art = { base = "cursor", bg = "", pic = nil, xV = 0, yV = 0, w = 64, rows = 1, x = 0, y = 0 },
		minigame = nil, grandma = nil, fortune = "Fortune #001", unshackle = "Unshackled cursors",
		synergies = {"Mice clicking mice"},
		tiered = { ["fortune"] = "Fortune #001" },
		tieredAchievs = {  },
		productionAchievs = { { pow = 1e19, name = "Click delegator" }, { pow = 1e26, name = "Finger clickin' good" }, { pow = 1e33, name = "Click (starring Adam Sandler)" } },
	},
	{ id = 1, name = "Grandma", plural = "grandmas", single = "grandma", bsingle = "grandma", bplural = "grandmas", desc = "A nice grandma to bake more cookies.",
		basePrice = 100, baseCps = 1, iconColumn = 1, icon = 1, n = 1,
		art = { base = "grandma", bg = "grandmaBackground.png", pic = nil, xV = 8, yV = 8, w = 32, rows = 3, x = 0, y = 16 },
		minigame = nil, grandma = nil, fortune = "Fortune #002", unshackle = "Unshackled grandmas",
		synergies = {"Script grannies"},
		tiered = { [1] = "Forwards from grandma", [2] = "Steel-plated rolling pins", [3] = "Lubricated dentures", [4] = "Prune juice", [5] = "Double-thick glasses", [6] = "Aging agents", [7] = "Xtreme walkers", [8] = "The Unbridling", [9] = "Reverse dementia", [10] = "Timeproof hair dyes", [11] = "Good manners", [12] = "Generation degeneration", [13] = "Visits", [14] = "Kitchen cabinets", [15] = "Foam-tipped canes", ["fortune"] = "Fortune #002" },
		tieredAchievs = { [1] = "Grandma's cookies", [2] = "Sloppy kisses", [3] = "Retirement home", [4] = "Friend of the ancients", [5] = "Ruler of the ancients", [6] = "The old never bothered me anyway", [7] = "The agemaster", [8] = "To oldly go", [9] = "Aged well", [10] = "101st birthday", [11] = "But wait 'til you get older", [12] = "Defense of the ancients", [13] = "Okay boomer", [14] = "They moistly come at night", [15] = "And now you're even older" },
		productionAchievs = { { pow = 1e19, name = "Gushing grannies" }, { pow = 1e26, name = "Panic at the bingo" }, { pow = 1e33, name = "Frantiquities" } },
	},
	{ id = 2, name = "Farm", plural = "farms", single = "farm", bsingle = "farm", bplural = "farms", desc = "Grows cookie plants from cookie seeds.",
		basePrice = 1100, baseCps = 8, iconColumn = 2, icon = 3, n = 2,
		art = { base = "farm", bg = "farmBackground.png", pic = "farm.png", xV = 8, yV = 8, w = 64, rows = 2, x = 0, y = 16 },
		minigame = "Garden", grandma = "Farmer grandmas", fortune = "Fortune #003", unshackle = "Unshackled farms",
		synergies = {"Future almanacs","Rain prayer","Magical botany","Infernal crops","Fertile minds"},
		tiered = { [1] = "Cheap hoes", [2] = "Fertilizer", [3] = "Cookie trees", [4] = "Genetically-modified cookies", [5] = "Gingerbread scarecrows", [6] = "Pulsar sprinklers", [7] = "Fudge fungus", [8] = "Wheat triffids", [9] = "Humane pesticides", [10] = "Barnstars", [11] = "Lindworms", [12] = "Global seed vault", [13] = "Reverse-veganism", [14] = "Cookie mulch", [15] = "Self-driving tractors", ["fortune"] = "Fortune #003" },
		tieredAchievs = { [1] = "Bought the farm", [2] = "Reap what you sow", [3] = "Farm ill", [4] = "Perfected agriculture", [5] = "Homegrown", [6] = "Gardener extraordinaire", [7] = "Seedy business", [8] = "You and the beanstalk", [9] = "Harvest moon", [10] = "Make like a tree", [11] = "Sharpest tool in the shed", [12] = "Overripe", [13] = "In the green", [14] = "It's grown on you", [15] = "Au naturel" },
		productionAchievs = { { pow = 100000000000000, name = "I hate manure" }, { pow = 1e21, name = "Rake in the dough" }, { pow = 1e28, name = "Overgrowth" } },
	},
	{ id = 3, name = "Mine", plural = "mines", single = "mine", bsingle = "mine", bplural = "mines", desc = "Mines out cookie dough and chocolate chips.",
		basePrice = 12000, baseCps = 47, iconColumn = 3, icon = 4, n = 3,
		art = { base = "mine", bg = "mineBackground.png", pic = "mine.png", xV = 16, yV = 16, w = 64, rows = 2, x = 0, y = 24 },
		minigame = nil, grandma = "Miner grandmas", fortune = "Fortune #004", unshackle = "Unshackled mines",
		synergies = {"Seismic magic","Asteroid mining","Fossil fuels","Primordial ores","Gemmed talismans"},
		tiered = { [1] = "Sugar gas", [2] = "Megadrill", [3] = "Ultradrill", [4] = "Ultimadrill", [5] = "H-bomb mining", [6] = "Coreforge", [7] = "Planetsplitters", [8] = "Canola oil wells", [9] = "Mole people", [10] = "Mine canaries", [11] = "Bore again", [12] = "Air mining", [13] = "Caramel alloys", [14] = "Delicious mineralogy", [15] = "Mineshaft supports", ["fortune"] = "Fortune #004" },
		tieredAchievs = { [1] = "You know the drill", [2] = "Excavation site", [3] = "Hollow the planet", [4] = "Can you dig it", [5] = "The center of the Earth", [6] = "Tectonic ambassador", [7] = "Freak fracking", [8] = "Romancing the stone", [9] = "Mine?", [10] = "Cave story", [11] = "Hey now, you're a rock", [12] = "Rock on", [13] = "Mountain out of a molehill, but like in a good way", [14] = "Don't let the walls cave in on you", [15] = "Dirt-rich" },
		productionAchievs = { { pow = 1e15, name = "Never dig down" }, { pow = 1e22, name = "Quarry on" }, { pow = 1e29, name = "Sedimentalism" } },
	},
	{ id = 4, name = "Factory", plural = "factories", single = "factory", bsingle = "factory", bplural = "factories", desc = "Produces large quantities of cookies.",
		basePrice = 130000, baseCps = 260, iconColumn = 4, icon = 5, n = 4,
		art = { base = "factory", bg = "factoryBackground.png", pic = "factory.png", xV = 8, yV = 0, w = 64, rows = 1, x = 0, y = -22 },
		minigame = "Dungeon", grandma = "Worker grandmas", fortune = "Fortune #005", unshackle = "Unshackled factories",
		synergies = {"Quantum electronics","Temporal overclocking","Printing presses","Shipyards"},
		tiered = { [1] = "Sturdier conveyor belts", [2] = "Child labor", [3] = "Sweatshop", [4] = "Radium reactors", [5] = "Recombobulators", [6] = "Deep-bake process", [7] = "Cyborg workforce", [8] = "78-hour days", [9] = "Machine learning", [10] = "Brownie point system", [11] = "\"Volunteer\" interns", [12] = "Behavioral reframing", [13] = "The infinity engine", [14] = "N-dimensional assembly lines", [15] = "Universal automation", ["fortune"] = "Fortune #005" },
		tieredAchievs = { [1] = "Production chain", [2] = "Industrial revolution", [3] = "Global warming", [4] = "Ultimate automation", [5] = "Technocracy", [6] = "Rise of the machines", [7] = "Modern times", [8] = "Ex machina", [9] = "In full gear", [10] = "In-cog-neato", [11] = "Break the mold", [12] = "Self-manmade man", [13] = "The wheels of progress", [14] = "Replaced by robots", [15] = "Bots build bots" },
		productionAchievs = { { pow = 1e16, name = "The incredible machine" }, { pow = 1e23, name = "Yes I love technology" }, { pow = 1e30, name = "Labor of love" } },
	},
	{ id = 5, name = "Bank", plural = "banks", single = "bank", bsingle = "bank", bplural = "banks", desc = "Generates cookies from interest.",
		basePrice = 1400000, baseCps = 1400, iconColumn = 15, icon = 6, n = 5,
		art = { base = "bank", bg = "bankBackground.png", pic = "bank.png", xV = 8, yV = 4, w = 56, rows = 1, x = 0, y = 13 },
		minigame = "Stock Market", grandma = "Banker grandmas", fortune = "Fortune #006", unshackle = "Unshackled banks",
		synergies = {"Contracts from beyond","Printing presses","Gold fund","Extra physics funding"},
		tiered = { [1] = "Taller tellers", [2] = "Scissor-resistant credit cards", [3] = "Acid-proof vaults", [4] = "Chocolate coins", [5] = "Exponential interest rates", [6] = "Financial zen", [7] = "Way of the wallet", [8] = "The stuff rationale", [9] = "Edible money", [10] = "Grand supercycles", [11] = "Rules of acquisition", [12] = "Altruistic loop", [13] = "Diminishing tax returns", [14] = "Cookie Points", [15] = "The big shortcake", ["fortune"] = "Fortune #006" },
		tieredAchievs = { [1] = "Pretty penny", [2] = "Fit the bill", [3] = "A loan in the dark", [4] = "Need for greed", [5] = "It's the economy, stupid", [6] = "Acquire currency", [7] = "The nerve of war", [8] = "And I need it now", [9] = "Treacle tart economics", [10] = "Save your breath because that's all you've got left", [11] = "Get the show on, get paid", [12] = "Checks out", [13] = "That's rich", [14] = "Financial prodigy", [15] = "Getting that bag" },
		productionAchievs = { { pow = 1e17, name = "Vested interest" }, { pow = 1e24, name = "Paid in full" }, { pow = 1e31, name = "Reverse funnel system" } },
	},
	{ id = 6, name = "Temple", plural = "temples", single = "temple", bsingle = "temple", bplural = "temples", desc = "Full of precious, ancient chocolate.",
		basePrice = 20000000, baseCps = 7800, iconColumn = 16, icon = 7, n = 6,
		art = { base = "temple", bg = "templeBackground.png", pic = "temple.png", xV = 8, yV = 4, w = 72, rows = 2, x = 0, y = -5 },
		minigame = "Pantheon", grandma = "Priestess grandmas", fortune = "Fortune #007", unshackle = "Unshackled temples",
		synergies = {"Rain prayer","Paganism","God particle","Mystical energies","Thoughts & prayers"},
		tiered = { [1] = "Golden idols", [2] = "Sacrifices", [3] = "Delicious blessing", [4] = "Sun festival", [5] = "Enlarged pantheon", [6] = "Great Baker in the sky", [7] = "Creation myth", [8] = "Theocracy", [9] = "Sick rap prayers", [10] = "Psalm-reading", [11] = "War of the gods", [12] = "A novel idea", [13] = "Apparitions", [14] = "Negatheism", [15] = "Temple traps", ["fortune"] = "Fortune #007" },
		tieredAchievs = { [1] = "Your time to shrine", [2] = "Shady sect", [3] = "New-age cult", [4] = "Organized religion", [5] = "Fanaticism", [6] = "Zealotry", [7] = "Wololo", [8] = "Pray on the weak", [9] = "Holy cookies, grandma!", [10] = "Vengeful and almighty", [11] = "My world's on fire, how about yours", [12] = "Living on a prayer", [13] = "Preaches and cream", [14] = "And I will pray to a big god", [15] = "The leader is good, the leader is great" },
		productionAchievs = { { pow = 1e18, name = "New world order" }, { pow = 1e25, name = "Church of Cookiology" }, { pow = 1e32, name = "Thus spoke you" } },
	},
	{ id = 7, name = "Wizard tower", plural = "wizard towers", single = "wizard tower", bsingle = "wizard tower", bplural = "wizard towers", desc = "Summons cookies with magic spells.",
		basePrice = 330000000, baseCps = 44000, iconColumn = 17, icon = 8, n = 7,
		art = { base = "wizardtower", bg = "wizardtowerBackground.png", pic = "wizardtower.png", xV = 16, yV = 16, w = 48, rows = 2, x = 0, y = 20 },
		minigame = "Grimoire", grandma = "Witch grandmas", fortune = "Fortune #008", unshackle = "Unshackled wizard towers",
		synergies = {"Seismic magic","Arcane knowledge","Magical botany","Light magic"},
		tiered = { [1] = "Pointier hats", [2] = "Beardlier beards", [3] = "Ancient grimoires", [4] = "Kitchen curses", [5] = "School of sorcery", [6] = "Dark formulas", [7] = "Cookiemancy", [8] = "Rabbit trick", [9] = "Deluxe tailored wands", [10] = "Immobile spellcasting", [11] = "Electricity", [12] = "Spelling bees", [13] = "Wizard basements", [14] = "Magical realism", [15] = "Polymorphism", ["fortune"] = "Fortune #008" },
		tieredAchievs = { [1] = "Bewitched", [2] = "The sorcerer's apprentice", [3] = "Charms and enchantments", [4] = "Curses and maledictions", [5] = "Magic kingdom", [6] = "The wizarding world", [7] = "And now for my next trick, I'll need a volunteer from the audience", [8] = "It's a kind of magic", [9] = "The Prestige", [10] = "Spell it out for you", [11] = "The meteor men beg to differ", [12] = "Higitus figitus migitus mum", [13] = "Magic thinking", [14] = "Shosple Colupis", [15] = "You don't think they could've used... it couldn't have been ma-" },
		productionAchievs = { { pow = 1e19, name = "Hocus pocus" }, { pow = 1e26, name = "Too many rabbits, not enough hats" }, { pow = 1e33, name = "Manafest destiny" } },
	},
	{ id = 8, name = "Shipment", plural = "shipments", single = "shipment", bsingle = "shipment", bplural = "shipments", desc = "Brings in fresh cookies from the cookie planet.",
		basePrice = 5100000000, baseCps = 260000, iconColumn = 5, icon = 9, n = 8,
		art = { base = "shipment", bg = "shipmentBackground.png", pic = "shipment.png", xV = 16, yV = 16, w = 64, rows = 1, x = 0, y = 0 },
		minigame = nil, grandma = "Cosmic grandmas", fortune = "Fortune #009", unshackle = "Unshackled shipments",
		synergies = {"Asteroid mining","Fossil fuels","Shipyards","Relativistic parsec-skipping"},
		tiered = { [1] = "Vanilla nebulae", [2] = "Wormholes", [3] = "Frequent flyer", [4] = "Warp drive", [5] = "Chocolate monoliths", [6] = "Generation ship", [7] = "Dyson sphere", [8] = "The final frontier", [9] = "Autopilot", [10] = "Restaurants at the end of the universe", [11] = "Universal alphabet", [12] = "Toroid universe", [13] = "Prime directive", [14] = "Cosmic foreground radiation", [15] = "At your doorstep in 30 minutes or your money back", ["fortune"] = "Fortune #009" },
		tieredAchievs = { [1] = "Expedition", [2] = "Galactic highway", [3] = "Far far away", [4] = "Type II civilization", [5] = "We come in peace", [6] = "Parsec-masher", [7] = "It's not delivery", [8] = "Make it so", [9] = "That's just peanuts to space", [10] = "Space space space space space", [11] = "Only shooting stars", [12] = "The incredible journey", [13] = "Is there life on Mars?", [14] = "False vacuum", [15] = "Signed, sealed, delivered" },
		productionAchievs = { { pow = 1e20, name = "And beyond" }, { pow = 1e27, name = "The most precious cargo" }, { pow = 1e34, name = "Neither snow nor rain nor heat nor gloom of night" } },
	},
	{ id = 9, name = "Alchemy lab", plural = "alchemy labs", single = "alchemy lab", bsingle = "alchemy lab", bplural = "alchemy labs", desc = "Turns gold into cookies!",
		basePrice = 75000000000, baseCps = 1600000, iconColumn = 6, icon = 10, n = 9,
		art = { base = "alchemylab", bg = "alchemylabBackground.png", pic = "alchemylab.png", xV = 16, yV = 16, w = 64, rows = 2, x = 0, y = 16 },
		minigame = nil, grandma = "Transmuted grandmas", fortune = "Fortune #010", unshackle = "Unshackled alchemy labs",
		synergies = {"Arcane knowledge","Primordial ores","Gold fund","Chemical proficiency"},
		tiered = { [1] = "Antimony", [2] = "Essence of dough", [3] = "True chocolate", [4] = "Ambrosia", [5] = "Aqua crustulae", [6] = "Origin crucible", [7] = "Theory of atomic fluidity", [8] = "Beige goo", [9] = "The advent of chemistry", [10] = "On second thought", [11] = "Public betterment", [12] = "Hermetic reconciliation", [13] = "Chromatic cycling", [14] = "Arcanized glassware", [15] = "The dose makes the poison", ["fortune"] = "Fortune #010" },
		tieredAchievs = { [1] = "Transmutation", [2] = "Transmogrification", [3] = "Gold member", [4] = "Gild wars", [5] = "The secrets of the universe", [6] = "The work of a lifetime", [7] = "Gold, Jerry! Gold!", [8] = "All that glitters is gold", [9] = "Worth its weight in lead", [10] = "Don't get used to yourself, you're gonna have to change", [11] = "We could all use a little change", [12] = "Just a phase", [13] = "Bad chemistry", [14] = "Metallic taste", [15] = "Sugar, spice, and everything nice" },
		productionAchievs = { { pow = 1e21, name = "Magnum Opus" }, { pow = 1e28, name = "The Aureate" }, { pow = 1e35, name = "I've got the Midas touch" } },
	},
	{ id = 10, name = "Portal", plural = "portals", single = "portal", bsingle = "portal", bplural = "portals", desc = "Opens a door to the Cookieverse.",
		basePrice = 1000000000000, baseCps = 10000000, iconColumn = 7, icon = 11, n = 10,
		art = { base = "portal", bg = "portalBackground.png", pic = "portal.png", xV = 32, yV = 32, w = 64, rows = 2, x = 0, y = 0 },
		minigame = nil, grandma = "Altered grandmas", fortune = "Fortune #011", unshackle = "Unshackled portals",
		synergies = {"Contracts from beyond","Paganism","Infernal crops","Abysmal glimmer","Perforated mille-feuille cosmos"},
		tiered = { [1] = "Ancient tablet", [2] = "Insane oatling workers", [3] = "Soul bond", [4] = "Sanity dance", [5] = "Brane transplant", [6] = "Deity-sized portals", [7] = "End of times back-up plan", [8] = "Maddening chants", [9] = "The real world", [10] = "Dimensional garbage gulper", [11] = "Embedded microportals", [12] = "His advent", [13] = "Domestic rifts", [14] = "Portal guns", [15] = "A way home", ["fortune"] = "Fortune #011" },
		tieredAchievs = { [1] = "A whole new world", [2] = "Now you're thinking", [3] = "Dimensional shift", [4] = "Brain-split", [5] = "Realm of the Mad God", [6] = "A place lost in time", [7] = "Forbidden zone", [8] = "H̸̷͓̳̳̯̟͕̟͍͍̣͡ḛ̢̦̰̺̮̝͖͖̘̪͉͘͡ ̠̦͕̤̪̝̥̰̠̫̖̣͙̬͘ͅC̨̦̺̩̲̥͉̭͚̜̻̝̣̼͙̮̯̪o̴̡͇̘͎̞̲͇̦̲͞͡m̸̩̺̝̣̹̱͚̬̥̫̳̼̞̘̯͘ͅẹ͇̺̜́̕͢s̶̙̟̱̥̮̯̰̦͓͇͖͖̝͘͘͞", [9] = "What happens in the vortex stays in the vortex", [10] = "Objects in the mirror dimension are closer than they appear", [11] = "Your brain gets smart but your head gets dumb", [12] = "Don't let me leave, Murph", [13] = "Reduced to gibbering heaps", [14] = "Swiss cheese", [15] = "Not even remotely close to Kansas anymore" },
		productionAchievs = { { pow = 1e22, name = "With strange eons" }, { pow = 1e29, name = "Ever more hideous" }, { pow = 1e36, name = "Which eternal lie" } },
	},
	{ id = 11, name = "Time machine", plural = "time machines", single = "time machine", bsingle = "time machine", bplural = "time machines", desc = "Brings cookies from the past, before they were even eaten.",
		basePrice = 14000000000000, baseCps = 65000000, iconColumn = 8, icon = 12, n = 11,
		art = { base = "timemachine", bg = "timemachineBackground.png", pic = "timemachine.png", xV = 32, yV = 32, w = 64, rows = 1, x = 0, y = 0 },
		minigame = nil, grandma = "Grandmas' grandmas", fortune = "Fortune #012", unshackle = "Unshackled time machines",
		synergies = {"Future almanacs","Temporal overclocking","Relativistic parsec-skipping","Primeval glow","Accelerated development"},
		tiered = { [1] = "Flux capacitors", [2] = "Time paradox resolver", [3] = "Quantum conundrum", [4] = "Causality enforcer", [5] = "Yestermorrow comparators", [6] = "Far future enactment", [7] = "Great loop hypothesis", [8] = "Cookietopian moments of maybe", [9] = "Second seconds", [10] = "Additional clock hands", [11] = "Nostalgia", [12] = "Split seconds", [13] = "Patience abolished", [14] = "Timeproof upholstery", [15] = "Rectifying a mistake", ["fortune"] = "Fortune #012" },
		tieredAchievs = { [1] = "Time warp", [2] = "Alternate timeline", [3] = "Rewriting history", [4] = "Time duke", [5] = "Forever and ever", [6] = "Heat death", [7] = "cookie clicker forever and forever a hundred years cookie clicker, all day long forever, forever a hundred times, over and over cookie clicker adventures dot com", [8] = "Way back then", [9] = "Invited to yesterday's party", [10] = "Groundhog day", [11] = "The years start coming", [12] = "Caveman to cosmos", [13] = "Back already?", [14] = "But the future refused to change", [15] = "I only meant to stay a while" },
		productionAchievs = { { pow = 1e23, name = "Spacetime jigamaroo" }, { pow = 1e30, name = "Be kind, rewind" }, { pow = 1e37, name = "D&eacute;j&agrave; vu" } },
	},
	{ id = 12, name = "Antimatter condenser", plural = "antimatter condensers", single = "antimatter condenser", bsingle = "antimatter condenser", bplural = "antimatter condensers", desc = "Condenses the antimatter in the universe into cookies.",
		basePrice = 170000000000000, baseCps = 430000000, iconColumn = 13, icon = 13, n = 12,
		art = { base = "antimattercondenser", bg = "antimattercondenserBackground.png", pic = "antimattercondenser.png", xV = 0, yV = 64, w = 64, rows = 1, x = 0, y = 0 },
		minigame = nil, grandma = "Antigrandmas", fortune = "Fortune #013", unshackle = "Unshackled antimatter condensers",
		synergies = {"Quantum electronics","God particle","Extra physics funding","Chemical proficiency","Charm quarks"},
		tiered = { [1] = "Sugar bosons", [2] = "String theory", [3] = "Large macaron collider", [4] = "Big bang bake", [5] = "Reverse cyclotrons", [6] = "Nanocosmics", [7] = "The Pulse", [8] = "Some other super-tiny fundamental particle? Probably?", [9] = "Quantum comb", [10] = "Baking Nobel prize", [11] = "The definite molecule", [12] = "Flavor itself", [13] = "Delicious pull", [14] = "Employee minification", [15] = "Candied atoms", ["fortune"] = "Fortune #013" },
		tieredAchievs = { [1] = "Antibatter", [2] = "Quirky quarks", [3] = "It does matter!", [4] = "Molecular maestro", [5] = "Walk the planck", [6] = "Microcosm", [7] = "Scientists baffled everywhere", [8] = "Exotic matter", [9] = "Downsizing", [10] = "A matter of perspective", [11] = "What a concept", [12] = "Particular tastes", [13] = "Nuclear throne", [14] = "What's the dark matter with you", [15] = "Not 20 years away forever" },
		productionAchievs = { { pow = 1e24, name = "Supermassive" }, { pow = 1e31, name = "Infinitesimal" }, { pow = 1e38, name = "Powers of Ten" } },
	},
	{ id = 13, name = "Prism", plural = "prisms", single = "prism", bsingle = "prism", bplural = "prisms", desc = "Converts light itself into cookies.",
		basePrice = 2.1e15, baseCps = 2900000000, iconColumn = 14, icon = 14, n = 13,
		art = { base = "prism", bg = "prismBackground.png", pic = "prism.png", xV = 16, yV = 4, w = 64, rows = 1, x = 0, y = 20 },
		minigame = nil, grandma = "Rainbow grandmas", fortune = "Fortune #014", unshackle = "Unshackled prisms",
		synergies = {"Abysmal glimmer","Primeval glow","Light magic","Mystical energies","Recursive mirrors"},
		tiered = { [1] = "Gem polish", [2] = "9th color", [3] = "Chocolate light", [4] = "Grainbow", [5] = "Pure cosmic light", [6] = "Glow-in-the-dark", [7] = "Lux sanctorum", [8] = "Reverse shadows", [9] = "Crystal mirrors", [10] = "Reverse theory of light", [11] = "Light capture measures", [12] = "Light speed limit", [13] = "Occam's laser", [14] = "Hyperblack paint", [15] = "Lab goggles but like cool shades", ["fortune"] = "Fortune #014" },
		tieredAchievs = { [1] = "Lone photon", [2] = "Dazzling glimmer", [3] = "Blinding flash", [4] = "Unending glow", [5] = "Rise and shine", [6] = "Bright future", [7] = "Harmony of the spheres", [8] = "At the end of the tunnel", [9] = "My eyes", [10] = "Optical illusion", [11] = "You'll never shine if you don't glow", [12] = "A light snack", [13] = "Making light of the situation", [14] = "Enlightenment", [15] = "Bright side of the Moon" },
		productionAchievs = { { pow = 1e25, name = "Praise the sun" }, { pow = 1e32, name = "A still more glorious dawn" }, { pow = 1e39, name = "Now the dark days are gone" } },
	},
	{ id = 14, name = "Chancemaker", plural = "chancemakers", single = "chancemaker", bsingle = "chancemaker", bplural = "chancemakers", desc = "Generates cookies out of thin air through sheer luck.",
		basePrice = 2.6e16, baseCps = 21000000000, iconColumn = 19, icon = 15, n = 14,
		art = { base = "chancemaker", bg = "chancemakerBackground.png", pic = "chancemaker.png", xV = 8, yV = 64, w = 64, rows = 2, x = 0, y = 0 },
		minigame = nil, grandma = "Lucky grandmas", fortune = "Fortune #015", unshackle = "Unshackled chancemakers",
		synergies = {"Gemmed talismans","Charm quarks","Tombola computing"},
		tiered = { [1] = "Your lucky cookie", [2] = "\"All Bets Are Off\" magic coin", [3] = "Winning lottery ticket", [4] = "Four-leaf clover field", [5] = "A recipe book about books", [6] = "Leprechaun village", [7] = "Improbability drive", [8] = "Antisuperstistronics", [9] = "Bunnypedes", [10] = "Revised probabilistics", [11] = "0-sided dice", [12] = "A touch of determinism", [13] = "On a streak", [14] = "Silver lining maximization", [15] = "Gambler's fallacy fallacy", ["fortune"] = "Fortune #015" },
		tieredAchievs = { [1] = "Lucked out", [2] = "What are the odds", [3] = "Grandma needs a new pair of shoes", [4] = "Million to one shot, doc", [5] = "As luck would have it", [6] = "Ever in your favor", [7] = "Be a lady", [8] = "Dicey business", [9] = "Maybe a chance in hell, actually", [10] = "Jackpot", [11] = "You'll never know if you don't go", [12] = "Tempting fate", [13] = "Flip a cookie. Chips, I win. Crust, you lose.", [14] = "Never tell me the odds", [15] = "Riding the Mersenne twister" },
		productionAchievs = { { pow = 1e26, name = "Fingers crossed" }, { pow = 1e33, name = "Just a statistic" }, { pow = 1e40, name = "Murphy's wild guess" } },
	},
	{ id = 15, name = "Fractal engine", plural = "fractal engines", single = "fractal engine", bsingle = "fractal engine", bplural = "fractal engines", desc = "Turns cookies into even more cookies.",
		basePrice = 3.1e17, baseCps = 150000000000, iconColumn = 20, icon = 16, n = 15,
		art = { base = "fractalEngine", bg = "fractalEngineBackground.png", pic = "fractalEngine.png", xV = 8, yV = 64, w = 64, rows = 1, x = 0, y = 0 },
		minigame = nil, grandma = "Metagrandmas", fortune = "Fortune #016", unshackle = "Unshackled fractal engines",
		synergies = {"Recursive mirrors","Mice clicking mice","Infraverses and superverses"},
		tiered = { [1] = "Metabakeries", [2] = "Mandelbrown sugar", [3] = "Fractoids", [4] = "Nested universe theory", [5] = "Menger sponge cake", [6] = "One particularly good-humored cow", [7] = "Chocolate ouroboros", [8] = "Nested", [9] = "Space-filling fibers", [10] = "Endless book of prose", [11] = "The set of all sets", [12] = "This upgrade", [13] = "A box", [14] = "Multiscale profiling", [15] = "The more they stay the same", ["fortune"] = "Fortune #016" },
		tieredAchievs = { [1] = "Self-contained", [2] = "Threw you for a loop", [3] = "The sum of its parts", [4] = "Bears repeating", [5] = "More of the same", [6] = "Last recurse", [7] = "Out of one, many", [8] = "An example of recursion", [9] = "For more information on this achievement, please refer to its title", [10] = "I'm so meta, even this achievement", [11] = "Never get bored", [12] = "Tautological", [13] = "In and of itself", [14] = "Blowing an Apollonian gasket", [15] = "Divide and conquer" },
		productionAchievs = { { pow = 1e27, name = "The needs of the many" }, { pow = 1e34, name = "Eating its own" }, { pow = 1e41, name = "We must go deeper" } },
	},
	{ id = 16, name = "Javascript console", plural = "javascript consoles", single = "javascript console", bsingle = "javascript console", bplural = "javascript consoles", desc = "Creates cookies from the very code this game was written in.",
		basePrice = 7.1e19, baseCps = 1100000000000, iconColumn = 32, icon = 17, n = 16,
		art = { base = "javascriptconsole", bg = "javascriptconsoleBackground.png", pic = "javascriptconsole.png", xV = 8, yV = 64, w = 14, rows = 1, x = 8, y = -32 },
		minigame = nil, grandma = "Binary grandmas", fortune = "Fortune #017", unshackle = "Unshackled javascript consoles",
		synergies = {"Script grannies","Tombola computing","Peer review"},
		tiered = { [1] = "The JavaScript console for dummies", [2] = "64bit arrays", [3] = "Stack overflow", [4] = "Enterprise compiler", [5] = "Syntactic sugar", [6] = "A nice cup of coffee", [7] = "Just-in-time baking", [8] = "cookies++", [9] = "Software updates", [10] = "Game.Loop", [11] = "eval()", [12] = "Your biggest fans", [13] = "Hacker shades", [14] = "PHP containment vats", [15] = "Simulation failsafes", ["fortune"] = "Fortune #017" },
		tieredAchievs = { [1] = "F12", [2] = "Variable success", [3] = "No comments", [4] = "Up to code", [5] = "Works on my machine", [6] = "Technical debt", [7] = "Mind your language", [8] = "Inconsolable", [9] = "Closure", [10] = "Dude what if we're all living in a simulation like what if we're all just code on a computer somewhere", [11] = "Taking the back streets", [12] = "Curly braces", [13] = "Duck typing", [14] = "Get with the program", [15] = "Pebcakes" },
		productionAchievs = { { pow = 1e28, name = "Inherited prototype" }, { pow = 1e35, name = "A model of document object" }, { pow = 1e42, name = "First-class citizen" } },
	},
	{ id = 17, name = "Idleverse", plural = "idleverses", single = "idleverse", bsingle = "idleverse", bplural = "idleverses", desc = "There's been countless other idle universes running alongside our own. You've finally found a way to hijack their production and convert whatever they've been making into cookies!",
		basePrice = 1.2e22, baseCps = 8300000000000, iconColumn = 33, icon = 18, n = 17,
		art = { base = "idleverse", bg = "idleverseBackground.png", pic = "idleverse.png", xV = 8, yV = 96, w = 48, rows = 2, x = 0, y = 0 },
		minigame = nil, grandma = "Alternate grandmas", fortune = "Fortune #018", unshackle = "Unshackled idleverses",
		synergies = {"Perforated mille-feuille cosmos","Infraverses and superverses"},
		tiered = { [1] = "Manifest destiny", [2] = "The multiverse in a nutshell", [3] = "All-conversion", [4] = "Multiverse agents", [5] = "Escape plan", [6] = "Game design", [7] = "Sandbox universes", [8] = "Multiverse wars", [9] = "Mobile ports", [10] = "Encapsulated realities", [11] = "Extrinsic clicking", [12] = "Universal idling", [13] = "Break the fifth wall", [14] = "Opposite universe", [15] = "The other routes to Rome", ["fortune"] = "Fortune #018" },
		tieredAchievs = { [1] = "They'll never know what hit 'em", [2] = "Well-versed", [3] = "Ripe for the picking", [4] = "Unreal", [5] = "Once you've seen one", [6] = "Spoils and plunder", [7] = "Nobody exists on purpose, nobody belongs anywhere", [8] = "Hyperspace expressway", [9] = "Versatile", [10] = "You are inevitable", [11] = "Away from this place", [12] = "Everywhere at once", [13] = "Reject reality, substitute your own", [14] = "Lost your cosmic marbles", [15] = "Greener on the other sides" },
		productionAchievs = { { pow = 1e29, name = "Fringe" }, { pow = 1e36, name = "Coherence" }, { pow = 1e43, name = "Earth-616" } },
	},
	{ id = 18, name = "Cortex baker", plural = "cortex bakers", single = "cortex baker", bsingle = "cortex baker", bplural = "cortex bakers", desc = "These artificial brains the size of planets are capable of simply dreaming up cookies into existence. Time and space are inconsequential. Reality is arbitrary.",
		basePrice = 1.9e24, baseCps = 64000000000000, iconColumn = 34, icon = 19, n = 18,
		art = { base = "cortex", bg = "cortexBackground.png", pic = "cortex.png", xV = 8, yV = 96, w = 48, rows = 1, x = 0, y = 0 },
		minigame = nil, grandma = "Brainy grandmas", fortune = "Fortune #019", unshackle = "Unshackled cortex bakers",
		synergies = {"Thoughts & prayers","Fertile minds"},
		tiered = { [1] = "Principled neural shackles", [2] = "Obey", [3] = "A sprinkle of irrationality", [4] = "Front and back hemispheres", [5] = "Neural networking", [6] = "Cosmic brainstorms", [7] = "Megatherapy", [8] = "Synaptic lubricant", [9] = "Psychokinesis", [10] = "Spines", [11] = "Neuraforming", [12] = "Epistemological trickery", [13] = "Every possible idea", [14] = "The land of dreams", [15] = "Intellectual property theft", ["fortune"] = "Fortune #019" },
		tieredAchievs = { [1] = "It's big brain time", [2] = "Just my imagination", [3] = "Now there's an idea", [4] = "The organ that named itself", [5] = "Gyrification", [6] = "A trademarked portmanteau of \"imagination\" and \"engineering\"", [7] = "Mindfulness", [8] = "The 10% myth", [9] = "Don't think about it too hard", [10] = "Though fools seldom differ", [11] = "Looking kind of dumb", [12] = "A beautiful mind", [13] = "Cardinal synapses", [14] = "By will alone I set my mind in motion", [15] = "Where is my mind" },
		productionAchievs = { { pow = 1e30, name = "Positive thinking" }, { pow = 1e37, name = "The thought that counts" }, { pow = 1e44, name = "Unthinkable" } },
	},
	{ id = 19, name = "You", plural = "You", single = "You", bsingle = "You", bplural = "You", desc = "You, alone, are the reason behind all these cookies. You figure if there were more of you... maybe you could make even more.",
		basePrice = 5.4e26, baseCps = 510000000000000, iconColumn = 35, icon = 20, n = 19,
		art = { base = "you", bg = "youBackground.png", pic = "you.png", xV = 0, yV = 0, w = 64, rows = 2, x = 0, y = 0 },
		minigame = nil, grandma = "Clone grandmas", fortune = "Fortune #020", unshackle = "Unshackled You",
		synergies = {"Accelerated development","Peer review"},
		tiered = { [1] = "Cloning vats", [2] = "Energized nutrients", [3] = "Stunt doubles", [4] = "Clone recycling plant", [5] = "Free-range clones", [6] = "Genetic tailoring", [7] = "Power in diversity", [8] = "Self-betterment", [9] = "Source control", [10] = "United workforce", [11] = "Safety patrols", [12] = "Clone rights", [13] = "One big family", [14] = "Fine-tuned body plans", [15] = "Reading your clones bedtime stories", ["fortune"] = "Fortune #020" },
		tieredAchievs = { [1] = "My own clone", [2] = "Multiplicity", [3] = "Born for this job", [4] = "Episode II", [5] = "Copy that", [6] = "Life finds a way", [7] = "Overcrowding", [8] = "Strength in numbers", [9] = "Army of me", [10] = "Know thyself", [11] = "Didn't make sense not to live", [12] = "Genetic bottleneck", [13] = "Despite everything, it's still you", [14] = "Everyone everywhere all at once", [15] = "Introspection" },
		productionAchievs = { { pow = 1e31, name = "Self-made" }, { pow = 1e38, name = "Reproducible results" }, { pow = 1e45, name = "That's all you" } },
	},
}

NS.TIERS = {
	[1] = { name = "Plain", unlock = 1, achievUnlock = 1, iconRow = 0, price = 10, special = false, req = nil, color = "#ccb3ac" },
	[2] = { name = "Berrylium", unlock = 5, achievUnlock = 50, iconRow = 1, price = 50, special = false, req = nil, color = "#ff89e7" },
	[3] = { name = "Blueberrylium", unlock = 25, achievUnlock = 100, iconRow = 2, price = 500, special = false, req = nil, color = "#00deff" },
	[4] = { name = "Chalcedhoney", unlock = 50, achievUnlock = 150, iconRow = 13, price = 50000, special = false, req = nil, color = "#ffcc2f" },
	[5] = { name = "Buttergold", unlock = 100, achievUnlock = 200, iconRow = 14, price = 5000000, special = false, req = nil, color = "#e9d673" },
	[6] = { name = "Sugarmuck", unlock = 150, achievUnlock = 250, iconRow = 15, price = 500000000, special = false, req = nil, color = "#a8bf91" },
	[7] = { name = "Jetmint", unlock = 200, achievUnlock = 300, iconRow = 16, price = 500000000000, special = false, req = nil, color = "#60ff50" },
	[8] = { name = "Cherrysilver", unlock = 250, achievUnlock = 350, iconRow = 17, price = 500000000000000, special = false, req = nil, color = "#f01700" },
	[9] = { name = "Hazelrald", unlock = 300, achievUnlock = 400, iconRow = 18, price = 5e17, special = false, req = nil, color = "#9ab834" },
	[10] = { name = "Mooncandy", unlock = 350, achievUnlock = 450, iconRow = 19, price = 5e20, special = false, req = nil, color = "#7e7ab9" },
	[11] = { name = "Astrofudge", unlock = 400, achievUnlock = 500, iconRow = 28, price = 5e24, special = false, req = nil, color = "#9a3316" },
	[12] = { name = "Alabascream", unlock = 450, achievUnlock = 550, iconRow = 30, price = 5e28, special = false, req = nil, color = "#c1a88c" },
	[13] = { name = "Iridyum", unlock = 500, achievUnlock = 600, iconRow = 31, price = 5e32, special = false, req = nil, color = "#adb1b3" },
	[14] = { name = "Glucosmium", unlock = 550, achievUnlock = 650, iconRow = 34, price = 5e36, special = false, req = nil, color = "#ff89e7" },
	[15] = { name = "Glimmeringue", unlock = 600, achievUnlock = 700, iconRow = 36, price = 5e40, special = false, req = nil, color = "#fffaa8" },
	["synergy1"] = { name = "Synergy I", unlock = 15, achievUnlock = nil, iconRow = 20, price = 200000, special = true, req = "Synergies Vol. I", color = "#008595" },
	["synergy2"] = { name = "Synergy II", unlock = 75, achievUnlock = nil, iconRow = 29, price = 200000000000, special = true, req = "Synergies Vol. II", color = "#008595" },
	["fortune"] = { name = "Fortune", unlock = -1, achievUnlock = nil, iconRow = 32, price = 7.777777777778e28, special = true, req = nil, color = "#9ab834" },
}
