-- MauCookie: seasons, dragon, Santa, eggs and other tables, generated from the original game's data (version 2.052).
-- Do not edit by hand; regenerate with scratchpad ccgen/gen-lua.js.

local _, NS = ...

NS.UNLOCK_AT = {
	{ cookies = 4.999995e4, name = "Plain cookies" },
	{ cookies = 2.4999975e5, name = "Sugar cookies" },
	{ cookies = 4.9999995e5, name = "Oatmeal raisin cookies" },
	{ cookies = 2.49999975e6, name = "Peanut butter cookies" },
	{ cookies = 4.99999995e6, name = "Coconut cookies" },
	{ cookies = 2.499999975e7, name = "White chocolate cookies" },
	{ cookies = 4.99999995e6, name = "Macadamia nut cookies" },
	{ cookies = 2.4999999975e8, name = "Double-chip cookies" },
	{ cookies = 4.9999999995e8, name = "White chocolate macadamia nut cookies" },
	{ cookies = 2.49999999975e9, name = "All-chocolate cookies" },
	{ cookies = 4.99999999995e9, name = "Dark chocolate-coated cookies" },
	{ cookies = 4.99999999995e9, name = "White chocolate-coated cookies" },
	{ cookies = 2.499999999975e10, name = "Eclipse cookies" },
	{ cookies = 4.999999999995e10, name = "Zebra cookies" },
	{ cookies = 2.499999999998e11, name = "Snickerdoodles" },
	{ cookies = 5e11, name = "Stroopwafels" },
	{ cookies = 2.5e12, name = "Macaroons" },
	{ cookies = 5e12, name = "Empire biscuits" },
	{ cookies = 5e12, name = "British tea biscuits", require = "Tin of british tea biscuits" },
	{ cookies = 5e12, name = "Chocolate british tea biscuits", require = "British tea biscuits" },
	{ cookies = 5e12, name = "Round british tea biscuits", require = "Chocolate british tea biscuits" },
	{ cookies = 5e12, name = "Round chocolate british tea biscuits", require = "Round british tea biscuits" },
	{ cookies = 5e12, name = "Round british tea biscuits with heart motif", require = "Round chocolate british tea biscuits" },
	{ cookies = 5e12, name = "Round chocolate british tea biscuits with heart motif", require = "Round british tea biscuits with heart motif" },
	{ cookies = 2.5e13, name = "Madeleines" },
	{ cookies = 2.5e13, name = "Palmiers" },
	{ cookies = 5e13, name = "Palets" },
	{ cookies = 5e13, name = "Sabl&eacute;s" },
	{ cookies = 500000000000000, name = "Caramoas", require = "Box of brand biscuits" },
	{ cookies = 500000000000000, name = "Sagalongs", require = "Box of brand biscuits" },
	{ cookies = 500000000000000, name = "Shortfoils", require = "Box of brand biscuits" },
	{ cookies = 500000000000000, name = "Win mints", require = "Box of brand biscuits" },
	{ cookies = 2.5e14, name = "Fig gluttons", require = "Box of brand biscuits" },
	{ cookies = 2.5e14, name = "Loreols", require = "Box of brand biscuits" },
	{ cookies = 2.5e14, name = "Jaffa cakes", require = "Box of brand biscuits" },
	{ cookies = 2.5e14, name = "Grease's cups", require = "Box of brand biscuits" },
	{ cookies = 500000000000000, name = "Gingerbread men" },
	{ cookies = 500000000000000, name = "Gingerbread trees" },
	{ cookies = 50000, name = "Pure heart biscuits", season = "valentines" },
	{ cookies = 50000000, name = "Ardent heart biscuits", require = "Pure heart biscuits", season = "valentines" },
	{ cookies = 50000000000, name = "Sour heart biscuits", require = "Ardent heart biscuits", season = "valentines" },
	{ cookies = 50000000000000, name = "Weeping heart biscuits", require = "Sour heart biscuits", season = "valentines" },
	{ cookies = 5e16, name = "Golden heart biscuits", require = "Weeping heart biscuits", season = "valentines" },
	{ cookies = 5e19, name = "Eternal heart biscuits", require = "Golden heart biscuits", season = "valentines" },
	{ cookies = 4.9995e2, name = "Rose macarons", require = "Box of macarons" },
	{ cookies = 4.9999995e5, name = "Lemon macarons", require = "Box of macarons" },
	{ cookies = 4.9999999995e8, name = "Chocolate macarons", require = "Box of macarons" },
	{ cookies = 5e11, name = "Pistachio macarons", require = "Box of macarons" },
	{ cookies = 500000000000000, name = "Hazelnut macarons", require = "Box of macarons" },
	{ cookies = 5e17, name = "Violet macarons", require = "Box of macarons" },
	{ cookies = 5e20, name = "Caramel macarons", require = "Box of macarons" },
	{ cookies = 5e23, name = "Licorice macarons", require = "Box of macarons" },
	{ cookies = 2.5e15, name = "Pure black chocolate cookies" },
	{ cookies = 2.5e15, name = "Pure white chocolate cookies" },
	{ cookies = 5e15, name = "Ladyfingers" },
	{ cookies = 2.5e16, name = "Tuiles" },
	{ cookies = 5e16, name = "Chocolate-stuffed biscuits" },
	{ cookies = 2.5e17, name = "Checker cookies" },
	{ cookies = 5e17, name = "Butter cookies" },
	{ cookies = 2.5e18, name = "Cream cookies" },
	{ cookies = 5e18, name = "Gingersnaps" },
	{ cookies = 2.5e19, name = "Cinnamon cookies" },
	{ cookies = 5e19, name = "Vanity cookies" },
	{ cookies = 2.5e20, name = "Cigars" },
	{ cookies = 5e20, name = "Pinwheel cookies" },
	{ cookies = 2.5e21, name = "Fudge squares" },
	{ cookies = 2.5e14, name = "Digits", require = "Box of brand biscuits" },
	{ cookies = 5e21, name = "Butter horseshoes", require = "Tin of butter cookies" },
	{ cookies = 2.5e22, name = "Butter pucks", require = "Tin of butter cookies" },
	{ cookies = 5e22, name = "Butter knots", require = "Tin of butter cookies" },
	{ cookies = 2.5e23, name = "Butter slabs", require = "Tin of butter cookies" },
	{ cookies = 5e23, name = "Butter swirls", require = "Tin of butter cookies" },
	{ cookies = 5e21, name = "Shortbread biscuits" },
	{ cookies = 2.5e22, name = "Millionaires' shortbreads" },
	{ cookies = 5e22, name = "Caramel cookies" },
	{ cookies = 2.5e20, name = "Lombardia cookies", require = "Box of brand biscuits" },
	{ cookies = 2.5e20, name = "Bastenaken cookies", require = "Box of brand biscuits" },
	{ cookies = 2.5e23, name = "Pecan sandies" },
	{ cookies = 5e23, name = "Moravian spice cookies" },
	{ cookies = 2.5e24, name = "Anzac biscuits" },
	{ cookies = 5e24, name = "Buttercakes" },
	{ cookies = 2.5e25, name = "Ice cream sandwiches" },
	{ cookies = 5e27, name = "Birthday cookie" },
	{ cookies = 5e25, name = "Pink biscuits" },
	{ cookies = 2.5e26, name = "Whole-grain cookies" },
	{ cookies = 5e26, name = "Candy cookies" },
	{ cookies = 2.5e27, name = "Big chip cookies" },
	{ cookies = 5e27, name = "One chip cookies" },
	{ cookies = 2.5e28, name = "Sprinkles cookies" },
	{ cookies = 5e28, name = "Peanut butter blossoms" },
	{ cookies = 2.5e29, name = "No-bake cookies" },
	{ cookies = 5e29, name = "Florentines" },
	{ cookies = 2.5e30, name = "Chocolate crinkles" },
	{ cookies = 5e30, name = "Maple cookies" },
	{ cookies = 2.5e23, name = "Festivity loops", require = "Box of brand biscuits" },
	{ cookies = 2.5e31, name = "Persian rice cookies" },
	{ cookies = 5e31, name = "Norwegian cookies" },
	{ cookies = 2.5e32, name = "Crispy rice cookies" },
	{ cookies = 5e32, name = "Ube cookies" },
	{ cookies = 2.5e33, name = "Butterscotch cookies" },
	{ cookies = 5e33, name = "Speculaas" },
	{ cookies = 2.5e34, name = "Chocolate oatmeal cookies" },
	{ cookies = 5e34, name = "Molasses cookies" },
	{ cookies = 2.5e35, name = "Biscotti" },
	{ cookies = 5e35, name = "Waffle cookies" },
	{ cookies = 4.99999995e6, name = "Almond cookies" },
	{ cookies = 4.99999995e6, name = "Hazelnut cookies" },
	{ cookies = 4.99999995e6, name = "Walnut cookies" },
	{ cookies = 2.5e36, name = "Custard creams" },
	{ cookies = 5e36, name = "Bourbon biscuits" },
	{ cookies = 2.5e37, name = "Mini-cookies" },
	{ cookies = 5e29, name = "Profiteroles", require = "Box of pastries" },
	{ cookies = 5e31, name = "Jelly donut", require = "Box of pastries" },
	{ cookies = 5e33, name = "Glazed donut", require = "Box of pastries" },
	{ cookies = 5e35, name = "Chocolate cake", require = "Box of pastries" },
	{ cookies = 5e37, name = "Strawberry cake", require = "Box of pastries" },
	{ cookies = 5e39, name = "Apple pie", require = "Box of pastries" },
	{ cookies = 5e41, name = "Lemon meringue pie", require = "Box of pastries" },
	{ cookies = 5e43, name = "Butter croissant", require = "Box of pastries" },
	{ cookies = 5e33, name = "Cookie dough", require = "Box of maybe cookies" },
	{ cookies = 5e35, name = "Burnt cookie", require = "Box of maybe cookies" },
	{ cookies = 5e37, name = "A chocolate chip cookie but with the chips picked off for some reason", require = "Box of maybe cookies" },
	{ cookies = 5e39, name = "Flavor text cookie", require = "Box of maybe cookies" },
	{ cookies = 5e41, name = "High-definition cookie", require = "Box of maybe cookies" },
	{ cookies = 5e32, name = "Toast", require = "Box of not cookies" },
	{ cookies = 5e34, name = "Peanut butter & jelly", require = "Box of not cookies" },
	{ cookies = 5e36, name = "Wookies", require = "Box of not cookies" },
	{ cookies = 5e38, name = "Cheeseburger", require = "Box of not cookies" },
	{ cookies = 5e40, name = "One lone chocolate chip", require = "Box of not cookies" },
	{ cookies = 5e37, name = "Whoopie pies" },
	{ cookies = 1.581138830084e38, name = "Caramel wafer biscuits" },
	{ cookies = 5e38, name = "Chocolate chip mocha cookies" },
	{ cookies = 1.581138830084e39, name = "Earl Grey cookies" },
	{ cookies = 5e39, name = "Corn syrup cookies" },
	{ cookies = 1.581138830084e40, name = "Icebox cookies" },
	{ cookies = 5e40, name = "Graham crackers" },
	{ cookies = 1.581138830084e41, name = "Hardtack" },
	{ cookies = 5e41, name = "Cornflake cookies" },
	{ cookies = 1.581138830084e42, name = "Tofu cookies" },
	{ cookies = 1.581138830084e42, name = "Gluten-free cookies" },
	{ cookies = 5e42, name = "Russian bread cookies" },
	{ cookies = 1.581138830084e43, name = "Lebkuchen" },
	{ cookies = 5e43, name = "Aachener Printen" },
	{ cookies = 1.581138830084e44, name = "Canistrelli" },
	{ cookies = 5e44, name = "Nice biscuits" },
	{ cookies = 1.581138830084e45, name = "French pure butter cookies" },
	{ cookies = 1.581138830084e45, name = "Petit beurre" },
	{ cookies = 5e45, name = "Nanaimo bars" },
	{ cookies = 1.581138830084e46, name = "Berger cookies" },
	{ cookies = 5e46, name = "Chinsuko" },
	{ cookies = 5e46, name = "Panda koala biscuits" },
	{ cookies = 1.581138830084e47, name = "Putri salju" },
	{ cookies = 5e47, name = "Milk cookies" },
	{ cookies = 5, name = "Cookie crumbs", require = "Legacy" },
	{ cookies = 50000000000, name = "Chocolate chip cookie", require = "Legacy" },
	{ cookies = 1.581138830084e48, name = "Kruidnoten" },
	{ cookies = 5e48, name = "Marie biscuits" },
	{ cookies = 1.581138830084e49, name = "Meringue cookies" },
	{ cookies = 5e42, name = "Pizza", require = "Box of not cookies" },
	{ cookies = 5e43, name = "Crackers", require = "Box of maybe cookies" },
	{ cookies = 2.5e26, name = "Havabreaks", require = "Box of brand biscuits" },
	{ cookies = 1.581138830084e39, name = "Chai tea cookies" },
	{ cookies = 5e49, name = "Yogurt cookies" },
	{ cookies = 1.581138830084e50, name = "Thumbprint cookies" },
	{ cookies = 5e50, name = "Pizzelle" },
	{ cookies = 2.5e29, name = "Zilla wafers", require = "Box of brand biscuits" },
	{ cookies = 2.5e32, name = "Dim Dams", require = "Box of brand biscuits" },
	{ cookies = 5e44, name = "Candy", require = "Box of not cookies" },
	{ cookies = 5e22, name = "Prism heart biscuits", require = "Eternal heart biscuits", season = "valentines" },
	{ cookies = 1.581138830084e51, name = "Granola cookies" },
	{ cookies = 5e51, name = "Ricotta cookies" },
	{ cookies = 1.581138830084e52, name = "Roze koeken" },
	{ cookies = 5e52, name = "Peanut butter cup cookies" },
	{ cookies = 1.581138830084e53, name = "Sesame cookies" },
	{ cookies = 5e53, name = "Taiyaki" },
	{ cookies = 1.581138830084e54, name = "Vanillekipferl" },
	{ cookies = 5e54, name = "Battenberg biscuits" },
	{ cookies = 1.581138830084e55, name = "Rosette cookies" },
	{ cookies = 5e55, name = "Gangmakers" },
	{ cookies = 1.581138830084e56, name = "Welsh cookies" },
	{ cookies = 5e56, name = "Raspberry cheesecake cookies" },
	{ cookies = 1.581138830084e57, name = "Bokkenpootjes" },
	{ cookies = 5e57, name = "Fat rascals" },
	{ cookies = 1.581138830084e58, name = "Ischler cookies" },
	{ cookies = 1.581138830084e58, name = "Matcha cookies" },
	{ cookies = 5e26, name = "Earl Grey macarons", require = "Box of macarons" },
	{ cookies = 2.5e35, name = "Pokey", require = "Box of brand biscuits" },
	{ cookies = 4.99999995e6, name = "Cashew cookies" },
	{ cookies = 2.499999975e7, name = "Milk chocolate cookies" },
	{ cookies = 5e58, name = "Dalgona cookies" },
	{ cookies = 1.581138830084e59, name = "Spicy cookies" },
	{ cookies = 5e59, name = "Smile cookies" },
	{ cookies = 1.581138830084e60, name = "Kolachy cookies" },
	{ cookies = 5e60, name = "Gomma cookies" },
	{ cookies = 1.581138830084e61, name = "Vegan cookies" },
	{ cookies = 5e61, name = "Coyotas" },
	{ cookies = 1.581138830084e62, name = "Frosted sugar cookies" },
	{ cookies = 5e62, name = "Marshmallow sandwich cookies" },
	{ cookies = 1.581138830084e63, name = "Web cookies" },
	{ cookies = 1.581138830084e63, name = "Steamed cookies" },
	{ cookies = 5e45, name = "Deep-fried cookie dough", require = "Box of maybe cookies" },
	{ cookies = 5e63, name = "Havreflarn" },
	{ cookies = 1.581138830084e64, name = "Alfajores" },
	{ cookies = 5e64, name = "Gaufrettes" },
	{ cookies = 1.581138830084e65, name = "Cookie bars" },
	{ cookies = 2.5e38, name = "Nines", require = "Box of brand biscuits" },
	{ cookies = 5e45, name = "Baklavas", require = "Box of pastries" },
	{ cookies = 5e65, name = "Snowball cookies" },
	{ cookies = 1.581138830084e66, name = "Sequilhos" },
	{ cookies = 5e66, name = "Hazelnut swirlies" },
	{ cookies = 1.581138830084e67, name = "Spritz cookies" },
	{ cookies = 5e67, name = "Mbatata cookies" },
	{ cookies = 1.581138830084e68, name = "Springerles" },
}

NS.GRANDMA_SYNERGIES = {"Farmer grandmas","Miner grandmas","Worker grandmas","Cosmic grandmas","Transmuted grandmas","Altered grandmas","Grandmas' grandmas","Antigrandmas","Rainbow grandmas","Banker grandmas","Priestess grandmas","Witch grandmas","Lucky grandmas","Metagrandmas","Binary grandmas","Alternate grandmas","Brainy grandmas","Clone grandmas"}
NS.BANK_ACHIEVEMENTS = {"Wake and bake","Making some dough","So baked right now","Fledgling bakery","Affluent bakery","World-famous bakery","Cosmic bakery","Galactic bakery","Universal bakery","Timeless bakery","Infinite bakery","Immortal bakery","Don't stop me now","You can stop now","Cookies all the way down","Overdose","How?","The land of milk and cookies","He who controls the cookies controls the universe","Tonight on Hoarders","Are you gonna eat all that?","We're gonna need a bigger bakery","In the mouth of madness","Brought to you by the letter <div style=\"display:inline-block;background:url(img/money.png);width:16px;height:16px;\"></div>","The dreams in which I'm baking are the best I've ever had","Set for life","Panic! at Nabisco","Bursting at the seams","Just about full","Hungry for more","Feed me, Orteil","And then what?","I think it's safe to say you've got it made","A sometimes food","Not enough of a good thing","Horn of plenty","Large and in charge","Absolutely stuffed","It's only wafer-thin","Think big","Hypersize me","Max capacity","Fake it till you bake it","History in the baking","What do you get for the baker who has everything","Bottomless pit","Rainy day fund","And a little extra"}
NS.CPS_ACHIEVEMENTS = {"Casual baking","Hardcore baking","Steady tasty stream","Cookie monster","Mass producer","Cookie vortex","Cookie pulsar","Cookie quasar","Oh hey, you're still here","Let's never bake again","A world filled with cookies","When this baby hits 36 quadrillion cookies per hour","Fast and delicious","Cookiehertz : a really, really tasty hertz","Woops, you solved world hunger","Turbopuns","Faster menner","And yet you're still hungry","The Abakening","There's really no hard limit to how long these achievement names can be and to be quite honest I'm rather curious to see how far we can go.<br>Adolphus W. Green (1844–1917) started as the Principal of the Groton School in 1864. By 1865, he became second assistant librarian at the New York Mercantile Library; from 1867 to 1869, he was promoted to full librarian. From 1869 to 1873, he worked for Evarts, Southmayd & Choate, a law firm co-founded by William M. Evarts, Charles Ferdinand Southmayd and Joseph Hodges Choate. He was admitted to the New York State Bar Association in 1873.<br>Anyway, how's your day been?","Fast","Knead for speed","Well the cookies start coming and they don't stop coming","I don't know if you've noticed but all these icons are very slightly off-center","The proof of the cookie is in the baking","If it's worth doing, it's worth overdoing","Running with scissors","Rarefied air","Push it to the limit","Green cookies sleep furiously","Leisurely pace","Hypersonic","Gotta go fast","Bake him away, toys","You're #1 so why try harder","Haven't even begun to peak","What did we even eat before these","Heavy flow","More you say?","Keep going until I say stop","But I didn't say stop, did I?","With unrivaled fervor","I am speed","And on and on","Everything happens so much","I'll rest when I'm dead","Can we get much higher","Speed's the name of the game (no it's not it's called Cookie Clicker)"}
NS.SANTA_DROPS = {"Increased merriness","Improved jolliness","A lump of coal","An itchy sweater","Reindeer baking grounds","Weighted sleighs","Ho ho ho-flavored frosting","Season savings","Toy workshop","Naughty list","Santa's bottomless bag","Santa's helpers","Santa's legacy","Santa's milk and cookies"}
NS.SANTA_LEVELS = {"Festive test tube","Festive ornament","Festive wreath","Festive tree","Festive present","Festive elf fetus","Elf toddler","Elfling","Young elf","Bulky elf","Nick","Santa Claus","Elder Santa","True Santa","Final Claus"}
NS.REINDEER_DROPS = {"Christmas tree biscuits","Snowflake biscuits","Snowman biscuits","Holly biscuits","Candy cane biscuits","Bell biscuits","Present biscuits"}
NS.EASTER_EGGS = {"Chicken egg","Duck egg","Turkey egg","Quail egg","Robin egg","Ostrich egg","Cassowary egg","Salmon roe","Frogspawn","Shark egg","Turtle egg","Ant larva","Golden goose egg","Faberge egg","Wrinklerspawn","Cookie egg","Omelette","Chocolate egg","Century egg","\"egg\""}
NS.EGG_DROPS = {"Chicken egg","Duck egg","Turkey egg","Quail egg","Robin egg","Ostrich egg","Cassowary egg","Salmon roe","Frogspawn","Shark egg","Turtle egg","Ant larva"}
NS.RARE_EGG_DROPS = {"Golden goose egg","Faberge egg","Wrinklerspawn","Cookie egg","Omelette","Chocolate egg","Century egg","\"egg\""}
NS.HALLOWEEN_DROPS = {"Skull cookies","Ghost cookies","Bat cookies","Slime cookies","Pumpkin cookies","Eyeball cookies","Spider cookies"}
NS.HEART_DROPS = {"Pure heart biscuits","Ardent heart biscuits","Sour heart biscuits","Weeping heart biscuits","Golden heart biscuits","Eternal heart biscuits","Prism heart biscuits"}

NS.SEASONS = {
	christmas = { name = "Christmas", start = "Christmas season has started!", over = "Christmas season is over.", trigger = "Festive biscuit" },
	valentines = { name = "Valentine's day", start = "Valentine's day has started!", over = "Valentine's day is over.", trigger = "Lovesick biscuit" },
	fools = { name = "Business day", start = "Business day has started!", over = "Business day is over.", trigger = "Fool's biscuit" },
	easter = { name = "Easter", start = "Easter season has started!", over = "Easter season is over.", trigger = "Bunny biscuit" },
	halloween = { name = "Halloween", start = "Halloween has started!", over = "Halloween is over.", trigger = "Ghostly biscuit" },
}

NS.DRAGON_LEVELS = {
	{ name = "Dragon egg", action = "Chip it", pic = 0, costStr = "1 million cookies" },
	{ name = "Dragon egg", action = "Chip it", pic = 1, costStr = "2 million cookies" },
	{ name = "Dragon egg", action = "Chip it", pic = 2, costStr = "4 million cookies" },
	{ name = "Shivering dragon egg", action = "Hatch it", pic = 3, costStr = "8 million cookies" },
	{ name = "Krumblor, cookie hatchling", action = "Train Breath of MilkAura: Kittens are 5% more effective.", pic = 4, costStr = "16 million cookies" },
	{ name = "Krumblor, cookie hatchling", action = "Train Dragon CursorAura: Clicking is 5% more powerful.", pic = 4, costStr = "100 cursors" },
	{ name = "Krumblor, cookie hatchling", action = "Train Elder BattalionAura: Grandmas gain +1% CpS for each non-grandma building.", pic = 4, costStr = "100 grandmas" },
	{ name = "Krumblor, cookie hatchling", action = "Train Reaper of FieldsAura: Golden cookies may trigger a Dragon Harvest.", pic = 4, costStr = "100 farms" },
	{ name = "Krumblor, cookie dragon", action = "Train Earth ShattererAura: Buildings sell back for 50% instead of 25%.", pic = 5, costStr = "100 mines" },
	{ name = "Krumblor, cookie dragon", action = "Train Master of the ArmoryAura: All upgrades are 2% cheaper.", pic = 5, costStr = "100 factories" },
	{ name = "Krumblor, cookie dragon", action = "Train Fierce HoarderAura: All buildings are 2% cheaper.", pic = 5, costStr = "100 banks" },
	{ name = "Krumblor, cookie dragon", action = "Train Dragon GodAura: +5% prestige level effect on CpS.", pic = 5, costStr = "100 temples" },
	{ name = "Krumblor, cookie dragon", action = "Train Arcane AuraAura: Golden cookies appear 5% more often.", pic = 5, costStr = "100 wizard towers" },
	{ name = "Krumblor, cookie dragon", action = "Train DragonflightAura: Golden cookies may trigger a Dragonflight.", pic = 5, costStr = "100 shipments" },
	{ name = "Krumblor, cookie dragon", action = "Train Ancestral MetamorphosisAura: Golden cookies give 10% more cookies.", pic = 5, costStr = "100 alchemy labs" },
	{ name = "Krumblor, cookie dragon", action = "Train Unholy DominionAura: Wrath cookies give 10% more cookies.", pic = 5, costStr = "100 portals" },
	{ name = "Krumblor, cookie dragon", action = "Train Epoch ManipulatorAura: Golden cookie effects last 5% longer.", pic = 5, costStr = "100 time machines" },
	{ name = "Krumblor, cookie dragon", action = "Train Mind Over MatterAura: Random drops are 25% more common.", pic = 5, costStr = "100 antimatter condensers" },
	{ name = "Krumblor, cookie dragon", action = "Train Radiant AppetiteAura: All cookie production multiplied by 2.", pic = 5, costStr = "100 prisms" },
	{ name = "Krumblor, cookie dragon", action = "Train Dragon's FortuneAura: +123% CpS per golden cookie on-screen, multiplicative.", pic = 5, costStr = "100 chancemakers" },
	{ name = "Krumblor, cookie dragon", action = "Train Dragon's CurveAura: +5% sugar lump growth. Sugar lumps are twice as likely to be unusual.", pic = 5, costStr = "100 fractal engines" },
	{ name = "Krumblor, cookie dragon", action = "Train Reality BendingAura: One tenth of every other dragon aura, combined.", pic = 5, costStr = "100 javascript consoles" },
	{ name = "Krumblor, cookie dragon", action = "Train Dragon OrbsAura: With no buffs and no golden cookies on screen, selling your most powerful building has 10% chance to summon one.", pic = 5, costStr = "100 idleverses" },
	{ name = "Krumblor, cookie dragon", action = "Train Supreme IntellectAura: Confers various powers to your minigames while active.See the bottom of each minigame for more details.", pic = 5, costStr = "100 cortex bakers" },
	{ name = "Krumblor, cookie dragon", action = "Train Dragon GutsAura: You can attract 2 more wrinklers.Wrinklers digest 20% more cookies.Wrinklers explode into 20% more cookies.", pic = 5, costStr = "100 You" },
	{ name = "Krumblor, cookie dragon", action = "Bake dragon cookieDelicious!", pic = 6, costStr = "50 of every building" },
	{ name = "Krumblor, cookie dragon", action = "Train secondary auraLets you use two dragon auras simultaneously", pic = 7, costStr = "200 of every building" },
	{ name = "Krumblor, cookie dragon", action = "Your dragon is fully trained.", pic = 8, costStr = "" },
}

NS.DRAGON_AURAS = {
	[0] = { name = "No aura", desc = "Select an aura from those your dragon knows.", pic = {0,7} },
	[1] = { name = "Breath of Milk", desc = "Kittens are 5% more effective.", pic = {18,25} },
	[2] = { name = "Dragon Cursor", desc = "Clicking is 5% more powerful.", pic = {0,25} },
	[3] = { name = "Elder Battalion", desc = "Grandmas gain +1% CpS for each non-grandma building.", pic = {1,25} },
	[4] = { name = "Reaper of Fields", desc = "Golden cookies may trigger a Dragon Harvest.", pic = {2,25} },
	[5] = { name = "Earth Shatterer", desc = "Buildings sell back for 50% instead of 25%.", pic = {3,25} },
	[6] = { name = "Master of the Armory", desc = "All upgrades are 2% cheaper.", pic = {4,25} },
	[7] = { name = "Fierce Hoarder", desc = "All buildings are 2% cheaper.", pic = {15,25} },
	[8] = { name = "Dragon God", desc = "+5% prestige level effect on CpS.", pic = {16,25} },
	[9] = { name = "Arcane Aura", desc = "Golden cookies appear 5% more often.", pic = {17,25} },
	[10] = { name = "Dragonflight", desc = "Golden cookies may trigger a Dragonflight.", pic = {5,25} },
	[11] = { name = "Ancestral Metamorphosis", desc = "Golden cookies give 10% more cookies.", pic = {6,25} },
	[12] = { name = "Unholy Dominion", desc = "Wrath cookies give 10% more cookies.", pic = {7,25} },
	[13] = { name = "Epoch Manipulator", desc = "Golden cookie effects last 5% longer.", pic = {8,25} },
	[14] = { name = "Mind Over Matter", desc = "Random drops are 25% more common.", pic = {13,25} },
	[15] = { name = "Radiant Appetite", desc = "All cookie production multiplied by 2.", pic = {14,25} },
	[16] = { name = "Dragon's Fortune", desc = "+123% CpS per golden cookie on-screen, multiplicative.", pic = {19,25} },
	[17] = { name = "Dragon's Curve", desc = "+5% sugar lump growth. Sugar lumps are twice as likely to be unusual.", pic = {20,25} },
	[18] = { name = "Reality Bending", desc = "One tenth of every other dragon aura, combined.", pic = {32,25} },
	[19] = { name = "Dragon Orbs", desc = "With no buffs and no golden cookies on screen, selling your most powerful building has 10% chance to summon one.", pic = {33,25} },
	[20] = { name = "Supreme Intellect", desc = "Confers various powers to your minigames while active.See the bottom of each minigame for more details.", pic = {34,25} },
	[21] = { name = "Dragon Guts", desc = "You can attract 2 more wrinklers.Wrinklers digest 20% more cookies.Wrinklers explode into 20% more cookies.", pic = {35,25} },
}

NS.ASCENSION_MODES = {
	[0] = { name = "None", desc = "No special modifiers.", icon = {10,0} },
	[1] = { name = "Born again", desc = "This run will behave as if you'd just started the game from scratch. Prestige levels and heavenly upgrades will have no effect, as will sugar lumps and building levels. Perma-upgrades and minigames will be unavailable.Some achievements are only available in this mode.", icon = {2,7} },
}
